### ISSUE TITLE
Ringtone volume is too low.

### ISSUE THREAD

**Issue by andreacastello** [peterzagoranski/flutter_ringtone#1]
The Ringtone methods works fine, but the ringtone volume level is too low, difficult to hear in many situations. Using the phone controls to raise the volume has no effect.
The test has been done on a Huawei P20 Pro.

**Comment by andreacastello** [comment]
Thanks for enhancing it! I guess it will take some time for version 0.0.2 to be out.

**Comment by peterzagoranski** [comment]
Try now ... https://pub.dev/packages/ringtone

**Comment by andreacastello** [comment]
It's OK. Thanks!
